const noop = () => { };
const toLowerCase = (value = '') => value.toLowerCase();

const defaultOptions = {
  log: noop,
  name: toLowerCase,

  decodeEntities: false,
  caseSensitive: false,

  removeTagWhitespace: false,
  quoteCharacter: null,

  removeAttributeQuotes: false,
  collapseBooleanAttributes: false,
  removeEmptyAttributes: false,
  preventAttributesEscaping: false,
  removeRedundantAttributes: false,
  removeScriptTypeAttributes: false,
  removeStyleLinkTypeAttributes: false,

  customEventAttributes: null,

  removeComments: false,

  minifyJS: null,
  minifyCSS: null,
  minifyURLs: null,

  keepClosingSlash: false,
  useShortDoctype: false,
  customAttrCollapse: null,

  // Below are not implemented or partially completed options
  sortAttributes: false,
  sortClassName: false,
  processScripts: null,

  ignoreCustomComments: [
    /^!/,
    /^\s*#/
  ],

  ignoreCustomFragments: [
    /<%[\s\S]*?%>/,
    /<\?[\s\S]*?\?>/
  ],

  // whitespace
  collapseWhitespace: false,
  collapseInlineTagWhitespace: true,
  conservativeCollapse: false,
  preserveLineBreaks: false,
  trimCustomFragments: false,

  removeEmptyElements: false,
  includeAutoGeneratedTags: true,
  html5: true // not sure how to handle this
};

export default defaultOptions;
